### ISSUE TITLE
labels:[] dosn't seem to be working

### ISSUE THREAD

**Issue by gunharth** [javiereguiluz/easybook#145]
I'm trying to hide all labels from the editions following the instructions as per the documentation. e.g:

``` yaml
print:
    format:         pdf
    labels:         []
```

Using version 5.0-DEV this doesn't have any effect - all labels are visible ...

I'm working around this with custom templates but it would be great to get a solution for this.

Cheers
