### ISSUE TITLE
Add a full-featured but easy-to-use theme engine

### ISSUE THREAD

**Issue by javiereguiluz** [javiereguiluz/easybook#28]
**easybook** includes just one single default theme for every edition type:

```
app/
  Resources/
    Themes/
        Epub2/
        Pdf/
        Html/
        HtmlChunked/
```

If you want to change the design of a book, you have to create your own theme (as explained in the documentation).

This proposal would bring a full-featured, powerful but easy to use theme engine to **easybook**. The initial available themes would be:
- `base`, base theme used by all the other themes.
- `clean` (default theme), simple and minimalistic.
- `bright`, vibrant and modern.
- `dark`, matte black, modern and elegant.
- `latex`, LaTeX style copycat (including the fonts).
- `tech`, modern theme suited for tech books
- `novel`, simple theme for novels and regular books.

The `base` theme can't be used, but is necessary to simplify the themes. Some themes (e.g. `latex`) will be complex, but most themes will only change their CSS stylesheet.

The user could select the theme for the whole book and/or for each edition:

```
book:
  # ...
  theme: bright
  # ...

  editions:
    ebook:
      type:  epub
      theme: tech
      # ...

    print:
      type:  pdf
      theme: latex
      # ...

    web:
      type:  html
      # no `theme` option. Use `book` value for `theme` option
```

Directory structure for the new themes:

```
app/
  Resources/
    Themes/
      Base/
          Epub2/
          Pdf/
          Html/
          HtmlChunked/
    Clean/
          Epub2/
          Pdf/
          Html/
          HtmlChunked/  
    Bright/
          Epub2/
          Pdf/
          Html/
          HtmlChunked/
      Dark/
          Epub2/
          Pdf/
          Html/
          HtmlChunked/
      Latex/
          Epub2/
          Pdf/
          Html/
          HtmlChunked/
      ...
```

There is no obligation to define all variants for each theme. One particular theme could focus solely on `epub` edition whereas another theme could be `pdf` only.
