### ISSUE TITLE
Allow `part` content type to define its own content

### ISSUE THREAD

**Issue by javiereguiluz** [javiereguiluz/easybook#48]
Usually, `part` content only display a title:

``` yaml
book:
  # ...
  contents:
    - { element: part, title: "My first book section/part" }
```

In some special cases, parts could also display contents (like a chapter or an appendix). The following should work:

``` yaml
book:
  # ...
  contents:
    - { element: part, title: "My first book section/part", content: "my-part-content.md" }
```
